<?php /** Title: Business services expanded / Slug: wp-bbtheme-child/business-services-expanded / Categories: wp-patterns-main, wp-theme-current */ ?>
<!-- wp:wpbb/row {"gutterX":"gx-5","gutterY":"gy-5","containerClass":"container","customClasses":"wp-theme-section-shell"} --><!-- wp:wpbb/column {"xs":12,"lg":5} --><!-- wp:paragraph {"className":"wp-theme-sector-eyebrow"} --><p class="wp-theme-sector-eyebrow"><?php echo esc_html__( 'Capabilities', 'wp-bbtheme-child' ); ?></p><!-- /wp:paragraph --><!-- wp:heading --><h2 class="wp-block-heading"><?php echo esc_html__( 'Strategy, design and delivery without the hand-offs.', 'wp-bbtheme-child' ); ?></h2><!-- /wp:heading --><!-- wp:paragraph --><p><?php echo esc_html__( 'A flexible service pattern for an agency, consultancy or specialist professional team.', 'wp-bbtheme-child' ); ?></p><!-- /wp:paragraph --><!-- /wp:wpbb/column --><!-- wp:wpbb/column {"xs":12,"lg":7} -->
<?php
$cards = array(
    array( '01', __( 'Strategy', 'wp-bbtheme-child' ), __( 'Research, proposition, content planning and a practical roadmap.', 'wp-bbtheme-child' ) ),
    array( '02', __( 'Design systems', 'wp-bbtheme-child' ), __( 'Distinct visual direction with reusable responsive components.', 'wp-bbtheme-child' ) ),
    array( '03', __( 'WordPress delivery', 'wp-bbtheme-child' ), __( 'Fast Gutenberg implementation with QA and maintainable editing.', 'wp-bbtheme-child' ) ),
);
foreach ( $cards as $card ) : ?><!-- wp:wpbb/bootstrap-div {"containerClass":"","utilityClasses":"wp-theme-sector-card business-service-row"} --><!-- wp:paragraph {"className":"wp-theme-card-number"} --><p class="wp-theme-card-number"><?php echo esc_html( $card[0] ); ?></p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading"><?php echo esc_html( $card[1] ); ?></h3><!-- /wp:heading --><!-- wp:paragraph --><p><?php echo esc_html( $card[2] ); ?></p><!-- /wp:paragraph --><!-- /wp:wpbb/bootstrap-div --><?php endforeach; ?><!-- /wp:wpbb/column --><!-- /wp:wpbb/row -->
